# Generated by Django 5.2 on 2025-04-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttypes',
            options={'managed': True},
        ),
    ]
